# Generated by Django 6.0.3 on 2026-03-14 15:09

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RouteAuditRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('origin', models.CharField(max_length=256)),
                ('destination', models.CharField(max_length=256)),
                ('fleet_type', models.CharField(choices=[('diesel', 'Diesel'), ('hybrid', 'Hybrid'), ('ev', 'EV')], max_length=16)),
                ('goal', models.CharField(choices=[('fastest', 'Fastest'), ('cheapest', 'Cheapest'), ('greenest', 'Greenest'), ('balanced', 'Balanced')], max_length=16)),
                ('restricted_zones_avoided', models.JSONField(default=list)),
                ('compliance_explanation', models.TextField()),
                ('estimated_cost_pence', models.PositiveIntegerField()),
                ('estimated_distance_km', models.DecimalField(decimal_places=2, max_digits=8)),
                ('estimated_duration_seconds', models.PositiveIntegerField()),
                ('emissions_kg_co2e', models.DecimalField(decimal_places=3, max_digits=10)),
                ('emissions_breakdown', models.JSONField(default=dict)),
            ],
        ),
    ]
